[package]
description = "Modified katana to match ArkProject requirement."
edition.workspace = true
license-file.workspace = true
name = "solis"
repository.workspace = true
version.workspace = true

[dependencies]
alloy-primitives.workspace = true
anyhow.workspace = true
async-trait = "0.1.57"
cainome = { git = "https://github.com/cartridge-gg/cainome", tag = "v0.2.6", features = [
    "abigen-rs",
] }
cfg-if = "1.0.0"
clap.workspace = true
clap_complete.workspace = true
common.workspace = true
console.workspace = true
dojo-metrics.workspace = true
dotenv = "0.15.0"
katana-core.workspace = true
katana-executor.workspace = true
katana-primitives.workspace = true
katana-rpc-api.workspace = true
katana-rpc.workspace = true
serde_json.workspace = true
shellexpand = "3.1.0"
starknet = "0.9.0"
starknet_api = "0.10.0"
tokio.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
url.workspace = true

[dev-dependencies]
assert_matches = "1.5.0"

[features]
default = [ "blockifier", "jemalloc", "messaging" ]

blockifier = [ "katana-executor/blockifier" ]
# Disable until SIR support Cairo 2.6.3
#sir = [ "katana-executor/sir" ]

jemalloc = [ "dojo-metrics/jemalloc" ]
messaging = [ "katana-core/messaging" ]
starknet-messaging = [ "katana-core/starknet-messaging", "messaging" ]
